version: "3.3"
services:
  postgres:
    image: "postgres:11"
    ports:
      - "54320:5432"
    volumes:
      - postgresdb:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: lexioapi_dev
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres
  api:
    build:
      context: .
    image: api:latest
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
        DATABASE_URL: postgresql://postgres:postgres@postgres:5432/lexioapi_dev?sslmode=disable
    depends_on:
      - postgres
volumes:
  postgresdb:

